import { PlatformNavbar } from '~/components/layout/navbar';
import { PlatformSidebar } from '~/components/layout/platform-sidebar';
import { SidebarProvider } from '~/components/ui/sidebar';
import type { Metadata } from 'next';
import { Zalando_Sans, Merriweather, IBM_Plex_Mono } from 'next/font/google';
import '../globals.css';
import { cn } from '~/lib/css';
import { Sidedock } from '../../components/layout/sidedock';

const fontSans = Zalando_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontSerif = Merriweather({
  subsets: ['latin'],
  variable: '--font-serif',
});

const fontMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PlatformLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-svh overflow-hidden font-sans antialiased',
        fontSans.variable,
        fontSerif.variable,
        fontMono.variable
      )}
    >
      <body className="flex h-svh max-h-svh flex-col overflow-hidden">
        <SidebarProvider>
          <div className="bg-background flex h-full min-h-0 w-full flex-col overflow-hidden">
            <PlatformNavbar />

            <div className="flex">
              <Sidedock />
              <PlatformSidebar />
              <main className="h-full w-full grow p-2">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
