import { PlatformNavbar } from '~/components/layout/navbar';
import { PlatformSidebar } from '~/components/layout/platform-sidebar';
import { SidebarProvider } from '~/components/ui/sidebar';
import type { Metadata } from 'next';
import '../globals.css';
import { Sidedock } from '~/components/layout/sidedock';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PlatformLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-svh overflow-hidden antialiased">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&family=Zalando+Sans:ital,wght@0,200..900;1,200..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="flex h-svh max-h-svh flex-col overflow-hidden">
        <SidebarProvider>
          <div className="bg-background flex h-full min-h-0 w-full flex-col overflow-hidden">
            <PlatformNavbar />

            <div className="flex">
              <Sidedock />
              <PlatformSidebar />
              <main className="h-full w-full grow p-2">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
